{{ $tls := fromYaml (include "everestOperator.tlsCerts" .) }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: everest-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ index $tls "ca.crt" }}
    service:
      name: everest-operator-webhook-service
      namespace: {{ include "everest.namespace" . }}
      path: /mutate-everest-percona-com-v1alpha1-databasecluster
  failurePolicy: Fail
  name: mdatabasecluster-v1alpha1.everest.percona.com
  rules:
  - apiGroups:
    - everest.percona.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ index $tls "ca.crt" }}
    service:
      name: everest-operator-webhook-service
      namespace: {{ include "everest.namespace" . }}
      path: /mutate-everest-percona-com-v1alpha1-dataimportjob
  failurePolicy: Fail
  name: mdataimportjobs-v1akpha1.everest.percona.com
  rules:
  - apiGroups:
    - everest.percona.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dataimportjobs
  sideEffects: None
