apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ include  "everest.namespace" . }}
type: kubernetes.io/tls
data: 
  {{- include "everestOperator.tlsCerts" . | trim | nindent 2 }}