{{- if (and .Values.server.tls.enabled .Values.server.tls.certificate.create -}}
{{- if .Values.server.tls.secret.create }}
{{ fail "cannot set both server.tls.secret.create and server.tls.certificate.create" }}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.server.tls.secretName }}
  namespace: {{ include  "everest.namespace" . }}
spec:
  {{- with .Values.server.tls.certificate.secretTemplateAnnotations }}
  secretTemplate:
    annotations:
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }} 
  secretName: {{ .Values.server.tls.secretName }}
  commonName: {{ .Values.server.tls.certificate.domain }}
  dnsNames:
    - {{ .Values.server.tls.certificate.domain }}
    {{- range .Values.server.tls.certificate.additionalHosts }}
    - {{ . | quote }}
    {{- end }}
  {{- with .Values.server.tls.certificate.duration }}
  duration: {{ . | quote }}
  {{- end }}
  {{- with .Values.server.tls.certificate.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  issuerRef:
    {{- with .Values.server.tls.certificate.issuer.group }}
    group: {{ . | quote }}
    {{- end }}
    kind: {{ .Values.server.tls.certificate.issuer.kind | quote }}
    name: {{ .Values.server.tls.certificate.issuer.name | quote }}
  {{- with .Values.server.tls.certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.server.tls.certificate.usages }}
  usages:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
