apiVersion: v1
kind: Service
metadata:
  name: everest
  namespace: {{ include  "everest.namespace" . }}
  labels:
    app.kubernetes.io/name: everest
    app.kubernetes.io/component: everest
spec:
  selector:
    app.kubernetes.io/name: everest-server
    app.kubernetes.io/component: everest-server
  type: ClusterIP
  ports:
  - protocol: TCP
    {{- if .Values.server.tls.enabled }}
    name: https
    port: 443
    {{- else }}
    port: {{ .Values.server.port }}
    name: http
    {{- end }}
    targetPort: {{ .Values.server.port }}
