# -- Namespace where OLM is installed. Do no change unless you know what you are doing.
namespace: everest-olm
# -- Image to use for Everest CatalogSource.
catalogSourceImage: percona/everest-catalog
# -- Image to use for the OLM components.
image: quay.io/operator-framework/olm@sha256:1b6002156f568d722c29138575733591037c24b4bfabc67946f268ce4752c3e6
packageserver:
  tls:
    # -- Type of TLS certificates. Supported values are "helm" and "cert-manager".
    # For production setup, it is recommended to use "cert-manager".
    type: "helm"
    # -- CA certificate for the PackageServer APIService. Overrides the tls.type setting.
    caCert: ""
    # -- Client certificate for the PackageServer APIService. Overrides the tls.type setting.
    tlsCert: ""
    # -- Client key for the PackageServer APIService. Overrides the tls.type setting.
    tlsKey: ""