{{- if (and .Release.IsUpgrade .Values.upgrade.crdChecks )}}
{{- $found := false }}
{{- range $index, $crd := (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "" ) }}
  {{- if (hasKey $crd.metadata.labels "everest.percona.com/crd") }}
    {{- $found = true }}
    {{- if ne $crd.metadata.labels."everest.percona.com/version" .Chart.Version }}
      {{ fail "Ensure that CRDs are upgraded first" }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if not $found }}
  {{ fail "No CRDs with the 'everest.percona.com/crd' annotation were found. Ensure that CRDs are upgraded first." }}
{{- end }}
{{- end }}